version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: